name: source-music
favicon: null
layout_spectrum: 0.3094903980381787
typography_spectrum: 0.10740055283531547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.44856386515311897
  lightness: 0.6147320778109133
  saturation: 0.1016116845421493
  rhythmicContrast: 0.8594417350832373
purpose: []
